data("AirPassengers")
class(AirPassengers)
start(AirPassengers)
end(AirPassengers)
summary(AirPassengers)
frequency(AirPassengers)
abline(reg=lm(AirPassengers~time(AirPassengers)))
cycle(AirPassengers)
plot(aggregate(AirPassengers, FUN=mean))
boxplot(AirPassengers~cycle(AirPassengers))